### ISSUE TITLE
hi,  how to choose another upskeller?

### ISSUE THREAD

**Issue by nikolaiusa** [alexv0iceh/AutoChar#1]
I have many other upskellers in my folder, how can I choose them?

I added the name to the line - I hope it will work there?

  ["Latent", "ESRGAN_4x", "R-ESRGAN 4x+Anime6B", "R-ESRGAN 4x+", "4x-UltraSharp", "4x_NMKD-Siax_200k", "None"], label="Upscaler 1",

**Comment by alexv0iceh** [comment]
Yeah, it will work just fine. I tried to make the list depending on user's present upscalers, but the way it's coded in Automatic1111 it will return INDEXES of upscalers, which I currently don't know how to convert into their names for generation parameter.
