### ISSUE TITLE
Cannot find R-ESRGAN 4x+Anime6B

### ISSUE THREAD

**Issue by mageofthesands** [alexv0iceh/AutoChar#2]
Script fails to find R-ESRGAN 4x+Anime6B.  But it's right there!  I even renamed RealESRGAN_x4plus_anime_6B to match it, and redownloaded RealESRGAN_x4plus_anime_6B just to make sure other things don't break.  It can find the other upscalers just fine though.
![Cannot Find the Anime](https://github.com/alexv0iceh/AutoChar/assets/81931767/eaeb1411-3904-4374-8f2e-81a4e06aaba2)

**Comment by Natans8** [comment]
I'm having the same issue

**Comment by leobut** [comment]
Same issue for me

**Comment by alexv0iceh** [comment]
Fixed in version 0.9, please enjoy and sorry for the wait!
