### ISSUE TITLE
face inpainting error.

### ISSUE THREAD

**Issue by GooseBBB** [alexv0iceh/AutoChar#3]
Getting this error last 2-3 days.
File "C:\sd\stable-diffusion-webui\modules\call_queue.py", line 55, in f

res = list(func(args, **kwargs))

File "C:\sd\stable-diffusion-webui\modules\call_queue.py", line 35, in f

res = func(args, *kwargs)

File "C:\sd\stable-diffusion-webui\modules\txt2img.py", line 54, in txt2img

processed = modules.scripts.scripts_txt2img.run(p,args)

File "C:\sd\stable-diffusion-webui\modules\scripts.py", line 456, in run

processed = script.run(p, *script_args)

File "C:\sd\stable-diffusion-webui\scripts\AutoChar_v08_release.py", line 437, in run

for (mask_face, mask_eyes, inpaint_face_size, inpaint_eye_size, face_found) in mask_create(

File "C:\sd\stable-diffusion-webui\scripts\AutoChar_v08_release.py", line 203, in mask_create

, faces = facedetector.detect(image)

cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\net_impl.cpp:279: error: (-204:Requested object was not found) Layer with requested id=-1 not found in function 'cv::dnn::dnn4_v20230620::Net::Impl::getLayerData'

**Comment by mageofthesands** [comment]
I started to get that error too today.  Not yesterday though.  I don't have anything like OpenCV on my D drive.  I installed OpenCV4.8, and it's still happening.  Only one inpainting.  

`2023-07-06 18:44:21,861 - ControlNet - INFO - Loading preprocessor: none
2023-07-06 18:44:21,862 - ControlNet - INFO - preprocessor resolution = 512
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [01:00<00:00,  2.14s/it]
Running DDIM Sampling with 9 timesteps██████████████████████████████████████████████████████████                         | 30/40 [01:07<00:17,  1.71s/it]
Decoding image:   0%|                                                                                                              | 0/9 [00:00<?, ?it/s]tensor(0.3606, device='privateuseone:0', dtype=torch.float16)
Decoding image:  11%|███████████▎                                                                                          | 1/9 [00:04<00:34,  4.28s/it]tensor(0.4470, device='privateuseone:0', dtype=torch.float16)██████████████████████████████████████▌                      | 31/40 [01:14<00:30,  3.43s/it]
Decoding image:  22%|██████████████████████▋                                                                               | 2/9 [00:07<00:27,  3.93s/it]tensor(0.5381, device='privateuseone:0', dtype=torch.float16)█████████████████████████████████████████                    | 32/40 [01:18<00:28,  3.50s/it]
Decoding image:  33%|██████████████████████████████████                                                                    | 3/9 [00:11<00:23,  3.88s/it]tensor(0.6309, device='privateuseone:0', dtype=torch.float16)███████████████████████████████████████████▌                 | 33/40 [01:22<00:25,  3.60s/it]
Decoding image:  44%|█████████████████████████████████████████████▎                                                        | 4/9 [00:15<00:19,  3.80s/it]tensor(0.7207, device='privateuseone:0', dtype=torch.float16)██████████████████████████████████████████████               | 34/40 [01:25<00:21,  3.63s/it]
Decoding image:  56%|████████████████████████████████████████████████████████▋                                             | 5/9 [00:19<00:15,  3.80s/it]tensor(0.8047, device='privateuseone:0', dtype=torch.float16)████████████████████████████████████████████████▌            | 35/40 [01:29<00:18,  3.68s/it]
Decoding image:  67%|████████████████████████████████████████████████████████████████████                                  | 6/9 [00:22<00:11,  3.76s/it]tensor(0.8804, device='privateuseone:0', dtype=torch.float16)███████████████████████████████████████████████████          | 36/40 [01:33<00:14,  3.68s/it]
Decoding image:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 7/9 [00:26<00:07,  3.73s/it]tensor(0.9453, device='privateuseone:0', dtype=torch.float16)█████████████████████████████████████████████████████▌       | 37/40 [01:37<00:11,  3.68s/it]
Decoding image:  89%|██████████████████████████████████████████████████████████████████████████████████████████▋           | 8/9 [00:30<00:03,  3.71s/it]tensor(0.9985, device='privateuseone:0', dtype=torch.float16)████████████████████████████████████████████████████████     | 38/40 [01:40<00:07,  3.67s/it]
Decoding image: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:33<00:00,  3.77s/it]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:22<00:00,  5.56s/it]
Total progress: 43it [02:23,  3.34s/it]
batch 0 of 1 batches [02:23,  6.41s/it]
2023-07-06 18:47:14,523 - ControlNet - INFO - Loading model from cache: controlnet11Models_openpose [73c2b67d]
2023-07-06 18:47:14,524 - ControlNet - INFO - Loading preprocessor: none
2023-07-06 18:47:14,524 - ControlNet - INFO - preprocessor resolution = 512
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 28/28 [00:58<00:00,  2.10s/it]
Running DDIM Sampling with 9 timesteps██████████████████████████████████████████████████████████                         | 30/40 [01:05<00:16,  1.67s/it]
Decoding image:   0%|                                                                                                              | 0/9 [00:00<?, ?it/s]tensor(0.3606, device='privateuseone:0', dtype=torch.float16)
Decoding image:  11%|███████████▎                                                                                          | 1/9 [00:04<00:32,  4.11s/it]tensor(0.4470, device='privateuseone:0', dtype=torch.float16)██████████████████████████████████████▌                      | 31/40 [01:13<00:29,  3.32s/it]
Decoding image:  22%|██████████████████████▋                                                                               | 2/9 [00:07<00:27,  3.87s/it]tensor(0.5381, device='privateuseone:0', dtype=torch.float16)█████████████████████████████████████████                    | 32/40 [01:16<00:27,  3.43s/it]
Decoding image:  33%|██████████████████████████████████                                                                    | 3/9 [00:11<00:22,  3.81s/it]tensor(0.6309, device='privateuseone:0', dtype=torch.float16)███████████████████████████████████████████▌                 | 33/40 [01:20<00:24,  3.52s/it]
Decoding image:  44%|█████████████████████████████████████████████▎                                                        | 4/9 [00:15<00:19,  3.83s/it]tensor(0.7207, device='privateuseone:0', dtype=torch.float16)██████████████████████████████████████████████               | 34/40 [01:24<00:21,  3.63s/it]
Decoding image:  56%|████████████████████████████████████████████████████████▋                                             | 5/9 [00:19<00:15,  3.75s/it]tensor(0.8047, device='privateuseone:0', dtype=torch.float16)████████████████████████████████████████████████▌            | 35/40 [01:27<00:18,  3.62s/it]
Decoding image:  67%|████████████████████████████████████████████████████████████████████                                  | 6/9 [00:22<00:11,  3.70s/it]tensor(0.8804, device='privateuseone:0', dtype=torch.float16)███████████████████████████████████████████████████          | 36/40 [01:31<00:14,  3.61s/it]
Decoding image:  78%|███████████████████████████████████████████████████████████████████████████████▎                      | 7/9 [00:26<00:07,  3.66s/it]tensor(0.9453, device='privateuseone:0', dtype=torch.float16)█████████████████████████████████████████████████████▌       | 37/40 [01:35<00:10,  3.61s/it]
Decoding image:  89%|██████████████████████████████████████████████████████████████████████████████████████████▋           | 8/9 [00:29<00:03,  3.66s/it]tensor(0.9985, device='privateuseone:0', dtype=torch.float16)████████████████████████████████████████████████████████     | 38/40 [01:38<00:07,  3.62s/it]
Decoding image: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:33<00:00,  3.72s/it]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:21<00:00,  5.48s/it]
Error completing request:17,  6.43s/it]
Arguments: ('task(8hu7bvqw0jjjhjd)', 'zoomed out, Young Gary Busey as a (wizard:1.3) in a low-budget 80s fantasy film, occult library in background, wild blonde hair, (masterpiece, best quality, high quality, highres, ultra-detailed), 1boy, <lora:80s_offset:1> AS-YoungV2, grin512, (photorealistic:1.2) (best quality) (detailed skin:1.3) (intricate details) (8k) (HDR) (analog film) (canon d5) (cinematic lighting) (sharp focus), ', 'NSFW, female, 1girl, bad legs, one leg, (bad face), low quality, blurry, out of focus, disfigured, weird hands, broken fingers, extra fingers, missing fingers, mutated hands, artist name, (worst quality, low quality, normal quality), FastNegativeV2 (monochrome) (bad hands) (disfigured) (grain) (poorly drawn) (mutilated) (lowres) (deformed) (dark) (lowpoly) (CG) (3d) (blurry) (duplicate) (watermark) (label) (signature) (frames) (text), ', [], 30, 15, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 440, 660, True, 0.3, 1.3, '4x_foolhardy_Remacri', 15, 0, 0, [], 1, True, False, True, False, True, False, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 32, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': <object object at 0x000002328489EA40>}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 32, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_module': 'inpaint_global_harmonious', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1, 'is_api': <object object at 0x000002328489D380>}, False, 'keyword prompt', 'iterate', 'None', 'textual inversion first', 'None', '1', 'None', False, 7, 100, 'Constant', 0, 'Constant', 0, 4, False, False, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, None, 'Refresh models', <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000232848B75B0>, False, '', 0.5, True, False, '', 'Lerp', False, False, False, 'Matrix', 'Horizontal', 'Mask', 'Prompt', '1,1', '0.2', False, False, False, 'Attention', False, '0', '0', '0.4', None, False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, 0, None, None, 1, False, 1, 0, '', '', 20, True, 20, True, 4, 0.4, 7, 512, 512, True, 88, False, 'None', True, 0.3, 'None', 0.55, 0.3, 0.2, 0.2, ['Automatic face inpaint'], False, 1.5, 1.2, False, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, 5, 'all', 'all', 'all', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', '20', 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', False, 'None', 'Not set', True, False, '', '', '', '', '', 1.3, 'Not set', 'Not set', 'Not set', 1, 1.3, 'Not set', 'Not set', 'Not set', 'Not set', 'Not set', 'Not set', 1.3, 1.3, 1.3, 'Not set', 'Not set', 1.3, True, True, 'Disabled', '', 5, 24, 12.5, 1000, '', 'DDIM', 0, 64, 64, '', 64, 7.5, 0.42, 'DDIM', 64, 64, 1, 0, 92, True, True, True, False, False, False, 'midas_v21_small', None, None, False, 50, True, 0, '', '', 20, True, 20, True, 4, 0.4, 7, 512, 512, True, 88, False, 'None') {}
Traceback (most recent call last):
  File "H:\stable-diffusion-webui-directml\modules\call_queue.py", line 57, in f
    res = list(func(*args, **kwargs))
  File "H:\stable-diffusion-webui-directml\modules\call_queue.py", line 37, in f
    res = func(*args, **kwargs)
  File "H:\stable-diffusion-webui-directml\modules\txt2img.py", line 53, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "H:\stable-diffusion-webui-directml\modules\scripts.py", line 408, in run
    processed = script.run(p, *script_args)
  File "H:\stable-diffusion-webui-directml\scripts\AutoChar_v08_release.py", line 437, in run
    for (mask_face, mask_eyes, inpaint_face_size, inpaint_eye_size, face_found) in mask_create(
  File "H:\stable-diffusion-webui-directml\scripts\AutoChar_v08_release.py", line 203, in mask_create
    _, faces = face_detector.detect(image)
cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\net_impl.cpp:279: error: (-204:Requested object was not found) Layer with requested id=-1 not found in function 'cv::dnn::dnn4_v20230620::Net::Impl::getLayerData'
`

**Comment by ccb2ku** [comment]
_, faces = face_detector.detect(image)
    cv2.error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\net_impl.cpp:279: error: (-204:Requested object was not found) Layer with requested id=-1 not found in function 'cv::dnn::dnn4_v20230620::Net::Impl::getLayerData'

I've also been getting the same cpp:279 error. Specifically after the image is generated and it tries to do the auto-char, the relevant part being:

**Comment by LadyFlames** [comment]
i fixed it the problem is Control net its incompatible with Autochar deleting Control net fixes it its a version mismatch Autochar uses opencv 4.7.0.2 while control net uses 4.8.0

**Comment by Gipofiz** [comment]
> i fixed it the problem is Control net its incompatible with Autochar deleting Control net fixes it its a version mismatch Autochar uses opencv 4.7.0.2 while control net uses 4.8.0

Can you write in detail how to fix it? Thanks a lot!

**Comment by LadyFlames** [comment]
all i did was uninstall Control Net entirely you can do that from the extension folder just delete the entire control net folder and restart your Web UI that will fix the issue

**Comment by leobut** [comment]
I have the same issue and deleting the controlnet folder alone does not solve the issue. I still get the same error after restarting automatic1111.

**Comment by LadyFlames** [comment]
well it worked for me but you might need to downgrade your OpenCV version to 4.7.0.2 since you had control net because its specifically made for 4.8.0

**Comment by leobut** [comment]
@LadyFlames 

I am unfortunalted not a python wizzard, so please bear with me 😄 

I checked the requirements.txt files in my local the automatic1111 folder and this all seems to be ok. I can't find the place in the repo where 4.8.0 is requested. I tried with a fresh venv and it still pulls 4.8.0. Do you maybe know where this is defined? Thanks a lot for your help ❤️

**Comment by leobut** [comment]
Thank you so much for this!

Here is what I did exactly in case someone has the same issue (I am on windows 11):

1. Open a terminal inside the root folder of stable-diffusion-webui
2. `.\venv\Scripts\activate`
3. `pip uninstall opencv` (it's ok if this command tells you that it's not installed, just skip it in that case)
4. `pip uninstall opencv_python`
5. `pip install opencv-python==4.7.0.72`
6. `pip install opencv-contrib-python==4.7.0.72`
7. `exit`
8. Open file `requirements.txt` in the root folder
9. Add a new line at the end with this content: `opencv-python`
10. Save & Close
11. Open `requirements_versions.txt` in the root folder
12. Add a new line at the end with this content: `opencv-python==4.7.0.72`
13. Save & Close
14. Start webui like normal
15. Enjoy face inpaint without errors 😆

**Comment by Praecordi** [comment]
I was just able to fix this. You can keep both by updating [opencv-python](https://pypi.org/project/opencv-python/) and [opencv-contrib-python](https://pypi.org/project/opencv-contrib-python/) to the latest version. And download the latest face_detection_yunet from [this page](https://github.com/opencv/opencv_zoo/blob/main/models/face_detection_yunet/face_detection_yunet_2023mar.onnx).

**Comment by alexv0iceh** [comment]
Fixed in version 0.9, please enjoy and sorry for the wait!
