### ISSUE TITLE
Can't get it working

### ISSUE THREAD

**Issue by ZachLoughery** [alexv0iceh/AutoChar#6]
Hi there,

I'm having a few issues. I've downloaded the latest version but first of all I'm getting an error that it cannot find any of the upscaler options except R-ESRGAN 4x, and secondly, when image generation finishes it breaks and I get this error message:

"error: OpenCV(4.8.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\net_impl.cpp:279: error: (-204:Requested object was not found) Layer with requested id=-1 not found in function 'cv::dnn::dnn4_v20230620::Net::Impl::getLayerData'"

I'm not sure why it's referring to my D:\ drive when I have nothing installed on it at present. The images come out completely broken with no evidence that the script has been doing its job. Would appreciate some help since your script seems very useful otherwise!

**Comment by jimmiles** [comment]
Same error here.

**Comment by alexv0iceh** [comment]
Fixed in version 0.9, please enjoy and sorry for the wait!

**Comment by jimmiles** [comment]
Which branch of A1111 are you supporting? And which extensions do you have?
Won't work for me still.
