### ISSUE TITLE
Everything after first LoRa gets completely removed from final prompt

### ISSUE THREAD

**Issue by Zedvia** [alexv0iceh/AutoChar#9]
When I start a generation it starts normally, but during the upscale (possibly during the LoRa lowering) everything after, and including, the first LoRa gets lost.

Example:
mountain, forest \<lora:add_details:1\> pine trees, walkway

gets transformed into:
mountain, forest

with everything after the first lora gone

**Comment by Zedvia** [comment]
Additional information: 
I also noticed that the "lower_lora" part only works correctly if there is no other text after the first lora.
Line 566 discards everything after the first LoRa which isn't also a LoRa.

**Comment by Zedvia** [comment]
#10 fixes the part of removing everything after the first LoRA while processing. For some reason the Meta Data and Filename still don't have the LoRAs in them

**Comment by alexv0iceh** [comment]
Thanks! It's really jarring about metadata, tried many times, but can't seem to get it right.
